map $http_upgrade $connection_upgrade {
	default upgrade;
	''      close;
}

server {
	listen 80;
	listen [::]:80;

	server_name localhost;

	root /usr/share/nginx/html;
	index index.html;

	ssi on;

	# Configurable redirect for /stem
	location /stem {
		return 302 ${VOTE_REDIRECT_URL};
	}

	# Proxy API requests to backend
	location /api/ {
		proxy_pass ${BACKEND_URL};
		proxy_set_header Host $host;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		rewrite ^/api/(.*)$ /$1 break;
	}

	location ~ ^/membership$ {
		return 301 /membership.html;
	}

	location / {
		try_files $uri $uri/ =404;
	}
}
