services:
  frontend:
    image: ghcr.io/suppen/bergenbrettspill-frontend:main
    container_name: bergenbrettspill-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      BACKEND_URL: ${BACKEND_URL}
      VOTE_REDIRECT_URL: ${VOTE_REDIRECT_URL}

  backend:
    image: ghcr.io/suppen/bergenbrettspill-backend:main
    container_name: bergenbrettspill-backend
    # The only file in `/data` is the database file. The DB is just a cache, so it's not really necessary to persist
    # it outside of the container.
    #volumes:
      #- ./data:/data
    restart: unless-stopped
    environment:
      BGG_GAME_LIST_USERNAME: ${BGG_GAME_LIST_USERNAME}
      BGG_TOKEN: ${BGG_TOKEN}
