FROM rust:1.93-bookworm

# Install dependencies
RUN apt-get update && apt-get install -y libpq-dev libsqlite3-dev ca-certificates && rm -rf /var/lib/apt/lists/*

# Install cargo-watch for auto-reloading
RUN cargo install cargo-watch

RUN mkdir /data
WORKDIR /app

ENV PORT=3000
ENV DB_PATH=/data/bbk.db
ENV RUST_BACKTRACE=1

EXPOSE 3000

CMD ["cargo", "watch", "-x", "run"]
